### ISSUE TITLE
No output when config lacks "repo" param

### ISSUE THREAD

**Issue by rochgs** [pantulis/tacoma#11]
Trying to switch to a project which configuration has no "repo" param ends execution without action nor output.

For example, with this .tacoma.yml:

```yaml
foo:
  aws_identity_file: "$HOME/.ssh/id_rsa"
  aws_secret_access_key: [real_key_here]
  aws_access_key_id: [real_key_id_here]
```

You get:

```
$> tacoma switch foo
$>
```

An error message would be appreciated.

Anyway, if you don't want to set a repo, you can use as workaround:

`repo: ""`
